version: '3.0'

volumes:
  psql.data:
    driver: local
  opennms.data:
    driver: local
  opennms.etc:
    driver: local
  cassandra1-data:
    driver: local

networks:
  opennms.net:
    driver: bridge

services:
  database:
    container_name: opennms.psql
    image: postgres:9.6
    env_file:
      - .postgres.env
    networks:
      - opennms.net
    volumes:
      - psql.data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"

  opennms:
    container_name: opennms.hzn.core.web
    # image: opennms/horizon-core-web:bleeding
    image: opennms21cassandra:latest
    
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - opennms.net
    depends_on:
      - database
      - cassandra1

    volumes:
      - opennms.etc:/opt/opennms/etc
      - opennms.data:/opennms-data
      - ./etc-overlay:/opt/opennms-etc-overlay
      
    # starting with cassandra option
    command: ["-c"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp"]
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"
      
  # using bitnami cassandra
  cassandra1:
      image: bitnami/cassandra:3.10-r7
      volumes:
        -  cassandra1-data:/bitnami/cassandra
      env_file:
         - .cassandra.env
      ports:
        - "7000:7000"
        - "7001:7001"
        - "9042:9042"
        - "9160:9160"
        - "7199:7199"
